# Generated by Django 6.0.4 on 2026-05-02 14:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'animal")),
                ('race', models.CharField(blank=True, max_length=100, verbose_name='Race')),
                ('sexe', models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle')], default='M', max_length=1, verbose_name='Sexe')),
                ('date_naissance_estimee', models.DateField(verbose_name='Date de naissance estimée')),
                ('vaccine', models.BooleanField(default=False, verbose_name='Vacciné')),
                ('sterilise', models.BooleanField(default=False, verbose_name='Stérilisé')),
                ('compatibilite_chats', models.BooleanField(default=False, verbose_name='Entente Chats')),
                ('compatibilite_chiens', models.BooleanField(default=False, verbose_name='Entente Chiens')),
                ('compatibilite_enfants', models.BooleanField(default=False, verbose_name='Entente Enfants')),
                ('statut', models.CharField(choices=[('Disponible', 'Disponible'), ('En soin', 'En soin'), ('Adopté', 'Adopté'), ("En famille d'accueil", "En famille d'accueil")], default='Disponible', max_length=50, verbose_name='Statut')),
                ('date_arrivee', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'arrivée")),
            ],
            options={
                'verbose_name_plural': 'Animaux',
            },
        ),
        migrations.CreateModel(
            name='Espece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_espece', models.CharField(max_length=100, unique=True, verbose_name="Nom de l'espèce")),
                ('besoins_specifiques', models.TextField(blank=True, verbose_name='Besoins spécifiques')),
            ],
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_adoptant', models.CharField(max_length=255, verbose_name="Nom de l'adoptant")),
                ('date_adoption', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'adoption")),
                ('frais_participation', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Frais de participation (€)')),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adoption', to='refuge.animal')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='espece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animaux', to='refuge.espece', verbose_name='Espèce'),
        ),
    ]
