# Generated by Django 6.0.4 on 2026-05-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refuge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='animaux/', verbose_name="Photo de l'animal"),
        ),
    ]
